### ISSUE TITLE
NaNs in statistics

### ISSUE THREAD

**Issue by dpo** [johnmyleswhite/Benchmarks.jl#14]
I'm getting this sort of result:

```
.================ Benchmark Results ========================
   Average elapsed time: 22189900966.00 ns
     95% CI for average: [NaN ns, NaN ns]
   Minimum elapsed time: 22189900966.00 ns
                GC time: 0.00%
       Memory allocated: 272000 bytes
  Number of allocations: 5000 allocations
      Number of samples: 1
        R² of OLS model: NaN
Time used for benchmark: 22.19s
            Precompiled: false
       Multiple samples: false
       Search performed: false
```

The CI and R^2 are NaN. This benchmark is basically just a loop around a `ccall()`.

**Comment by dpo** [comment]
It would also be useful to display human-readable times, e.g., switch units or otherwise.

**Comment by johnmyleswhite** [comment]
Hi @dpo, can you hold off using this package? It's not public yet for a reason. You're reporting issues that aren't true on the development branch, which will reflect the final public API.

**Comment by johnmyleswhite** [comment]
Will be addressed in first public release.
