### ISSUE TITLE
Reporting [0.0, 0.0] C.I for small functions on Windows.

### ISSUE THREAD

**Issue by KristofferC** [johnmyleswhite/Benchmarks.jl#2]
I realize this is not done yet so please tell if you do not wish to get any issues yet.

Anyway, I just tried on my KDTrees package and get this;

``` julia
julia> Benchmarks.@benchmark(knn(tree, rand(3), 10))
=== Benchmarking results ===
Sampling strategy: direct sampling
Number of samples: 100
Direct CI = [0.00 ms, 0.00 ms]
```

Actually, the same happens for

``` julia
Benchmarks.@benchmark(sin(2.0))
```

I guess the function that is supposed to step up the number of samples for fast functions is not working correctly?

**Comment by johnmyleswhite** [comment]
That's very strange. Can you try stepping through the code in `test/core.jl` and see what happens? On my system `Benchmarks.@benchmark(sin(2.0))` already works.

**Comment by KristofferC** [comment]
Just to add, this is on a Windows 7 computer with newest Nightly.

**Comment by KristofferC** [comment]
Also, longer functions seem to work ok:

``` julia
julia> Benchmarks.@benchmarkable(
           svd2_benchmark!,
           nothing,
           svd(randn(100, 100)),
           nothing
       )
svd2_benchmark! (generic function with 1 method)

julia>

julia> r = Benchmarks.execute(svd2_benchmark!)
=== Benchmarking results ===
Sampling strategy: direct sampling
Number of samples: 100
Direct CI = [6.58 ms, 6.89 ms]
```

**Comment by johnmyleswhite** [comment]
Oh, I think this code might not work at all on Windows computers. Certainly the Profiler does weird tricks on Windows. I think I'll need to work with somebody using Windows to figure out what (if anything) we can do to make this work on Windows.

**Comment by johnmyleswhite** [comment]
Potentially useful information: what does `Benchmarks.estimate_clock_resolution()` return on Windows?

**Comment by KristofferC** [comment]
Yeah I just tried that. It gives 0.0.

**Comment by johnmyleswhite** [comment]
Does `Benchmarks.estimate_clock_resolution(1)` also return `0.0`?

**Comment by KristofferC** [comment]
Repeatedly calling

```
function f()
    t1 = Base.time_ns()
    t2 = Base.time_ns()
    elapsed = convert(Float64, t2 - t1)
end
```

gives something like

```
julia> f()
0.0

julia> f()
0.0

julia> f()
311.0

julia> f()
311.0
```

so sometimes 0.0, sometimes 311.0.

**Comment by johnmyleswhite** [comment]
`311.0` is in the range I'm used to seeing on OS X. I'm not really sure what to think about getting `0.0` back.

**Comment by KristofferC** [comment]
But it is always exactly 311.0. I guess one "tick" is 311 ns and if it happens to run both `time_ns()` within 311 ns then it returns 0.

**Comment by johnmyleswhite** [comment]
What are the values returned by `Base.time_ns()`?

**Comment by johnmyleswhite** [comment]
``` jl
julia> f()
275.0

julia> f()
304.0

julia> f()
482.0

julia> f()
404.0

julia> f()
400.0

julia> f()
404.0

julia> f()
402.0

julia> f()
402.0

julia> f()
414.0

julia> f()
402.0

julia> f()
402.0

julia> f()
260.0
```

That's the kind of variability I see on OS X.

**Comment by KristofferC** [comment]
With:

``` julia
function f()
    t1 = Base.time_ns()
    t2 = Base.time_ns()
    println(t1)
    println(t2)
    elapsed = convert(Float64, t2 - t1)
end
```

``` julia
julia> f()
780361277834761
780361277834761
0.0

julia> f()
780361953881226
780361953881226
0.0

julia> f()
780362573919791
780362573920102
311.0
```

**Comment by johnmyleswhite** [comment]
``` jl
julia> f()
273837986459366
273837986459689
323.0

julia> f()
273838628350990
273838628351209
219.0

julia> f()
273839173040120
273839173040540
420.0

julia> f()
273839629283441
273839629283852
411.0

julia> f()
273840117014753
273840117015161
408.0

julia> f()
273840565127431
273840565127861
430.0

julia> f()
273840997024627
273840997025058
431.0

julia> f()
273841437077381
273841437077786
405.0
```

Ugh. Fixing this seems to require using something other than `time_ns` on Windows.

Thank you for following up with so much useful information. I've got a better sense of what to do now.

Let me cycle back to this issue later. I'd like to make sure the package works well on OS X first. Since I don't even own a Windows machine, doing any deeper debugging is going to require some more collaboration.

**Comment by KristofferC** [comment]
Sure, no problem. I do most my dev on Linux anyway, just happened to sit on a Windows computer right now.

**Comment by johnmyleswhite** [comment]
(y)

**Comment by SimonDanisch** [comment]
This seems to show the same behaviour as time_ns:

``` Julia
function query_performance_frequency()
    out = Ref{Int64}(0)
    ccall((:QueryPerformanceFrequency, "Kernel32"), Bool, (Ptr{Int},), out)
    out[]
end
function query_performance_counter()
    out = Ref{Int64}(0)
    ccall((:QueryPerformanceCounter, "Kernel32"), Bool, (Ptr{Int},), out)
    out[]
end
function to_microseconds(elapsed)
    frequency = query_performance_frequency()
    elapsed *= 10.0^6;
    elapsed /= frequency
end
```

``` julia
t0 = query_performance_counter()
t1 = query_performance_counter()
t0-t1 # between 0 and 1 ticks
```

It seems to be the best option though, from a quick research...

This seems to be better:

``` Julia
function highprecision_ticks()
    Base.llvmcall("""
        %tick = call i64 @llvm.readcyclecounter()
        ret i64 %tick
        """, Uint64, Tuple{}
    )
end
```

Though, microsoft strongly discourages the use of this ;)

https://msdn.microsoft.com/en-us/library/windows/desktop/dn553408(v=vs.85).aspx

**Comment by tomasaschan** [comment]
I happen to have a Macbook on which I run Windows, so I seem to be a good candidate for helping out with testing here :P However, I have little to no knowledge of what to try, but if there's a branch or code snippet that you want me to try out, feel free to ping me.

EDIT:

Yeah, the clock resolution is clearly confused on my machine - look at the lower bound for this time interval...

``` jl
julia> workspace(); using Benchmarks; @benchmark cos(2.0)^3
================ Benchmark Results ========================
     Time per evaluation: 29.34 ns [-30.66 ns, 89.34 ns]
Proportion of time in GC: NaN% [0.00%, 100.00%]
        Memory allocated: 0.00 bytes
   Number of allocations: 0 allocations
       Number of samples: 100
   Number of evaluations: 100
 Time spent benchmarking: 0.01 s
```

**Comment by johnmyleswhite** [comment]
As far as I understand the situation, I believe we need to upgrade libuv in Base to get `time_ns` to work well on Windows. But that may not be great. What is certainly true is that we need a robust timer function on Windows before we can do anything else.
