### ISSUE TITLE
Tests fail when trying to update to 0.4 - how do I fix?

### ISSUE THREAD

**Issue by tomasaschan** [johnmyleswhite/Benchmarks.jl#20]
I decided to try to fix all the deprecation warnings etc for 0.4. However, when I run the test suite on my laptop, the test for `estimate_clock_resolution` fails because [the two consecutive calls to `Base.time_ns()`](https://github.com/johnmyleswhite/Benchmarks.jl/blob/master/src/01_clock_resolution.jl#L22-L23) sometimes returns the same value, yielding `Δt == 0x0000000000000000`.

How do I fix that?

**Comment by KristofferC** [comment]
#2 is relevant

**Comment by tomasaschan** [comment]
Ah, thanks - I hadn't read that carefully enough to realize it was the same thing. I'll just disable that test for now, and come back to it once #2 is resolved
