### ISSUE TITLE
v0.5-dev+3961: @benchmark fn(a) is a syntax error

### ISSUE THREAD

**Issue by Jeffrey-Sarnoff** [johnmyleswhite/Benchmarks.jl#45]
v0.5.0-dev+3961 on Linux and Windows
function two() 2 end
@benchmark two()  # works
function add1(x) x+1 end
@benchmark add1(7)
ERROR: syntax: "(escape ##arg_1#331)" is not a valid function argument name
    in eval(::Module, ::Any) at ./boot.jl:230
a=7
@benchmark add1(a)
ERROR: syntax: "(escape ##arg_1#335)" is not a valid function argument name
    in eval(::Module, ::Any) at ./boot.jl:230

**Comment by yuyichao** [comment]
Please quote your code....
